version: '3.9'

services:
  auction-portal:
    depends_on:
      - auction_portal_postgres
      - auctionportal_redis
      - auction-portal-azurite
    build:
      context: .
      target: production
      dockerfile: AuctionPortal/Dockerfile
    image: auction-portal
    container_name: auction-portal
    environment:
      # ASP.NET Core
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ASPNETCORE_HTTPS_PORTS=${ASPNETCORE_HTTPS_PORTS}

      # Application Settings
      - ConnectionStrings__DefaultConnection=${POSTGRESQL_CONNECTION_STRING}
      - ConnectionStrings__Redis=${REDIS_CONNECTION_STRING}
      - ConnectionStrings__AzureStorage=${AZURE_STORAGE_CONNECTION_STRING}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

    ports:
      - "${ASPNETCORE_HTTP_PORTS}:8080"
      - "${ASPNETCORE_HTTPS_PORTS}:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  auction_portal_postgres:
    image: postgres:15
    container_name: auction_portal_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=auction_portal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ppp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auctionportal_redis:
    image: redis:7.2
    container_name: auctionportal_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  auction-portal-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: auction-portal-azurite
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/workspace
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /workspace --debug /workspace/debug.log

volumes:
  pgdata:
  redis_data:
  azurite_data:
